FROM openjdk:17-alpine

ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_EMAIL_PASSWORD
ARG POLYGON_API_KEY
ARG FINNHUB_IO_API_KEY
ARG EXCHANGE_RATE_API_KEY

ENV SPRING_DATASOURCE_URL: ${MONETA_DB_URL}
ENV SPRING_DATASOURCE_USERNAME: ${MONETA_DB_USER}
ENV SPRING_DATASOURCE_PASSWORD: ${MONETA_DB_PASSWORD}
ENV SPRING_EMAIL_PASSWORD: ${MONETA_EMAIL_AUTH}
ENV POLYGON_API_KEY: ${POLYGON_API_KEY}
ENV FINNHUB_IO_API_KEY: ${FINNHUB_API_KEY}
ENV EXCHANGE_RATE_API_KEY: ${EXCHANGE_API_KEY}

RUN mkdir /app

COPY moneta-0.0.1.jar /app/moneta-0.0.1.jar
WORKDIR /app

EXPOSE 8080
EXPOSE 587

LABEL authors="begjosip"
ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "moneta-0.0.1.jar"]