name: Build and publish Docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    name: Build docker image and publish to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Build
        run: ./gradlew build
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.MONETA_DB_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.MONETA_DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MONETA_DB_PASSWORD }}
          SPRING_EMAIL_PASSWORD: ${{ secrets.MONETA_EMAIL_AUTH }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          FINNHUB_IO_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          EXCHANGE_RATE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}

      - name: Copy Jar file
        run: mv build/libs/moneta-0.0.1.jar moneta-0.0.1.jar

      - uses: actions/upload-artifact@master
        with:
          name: jar-file
          path: moneta-0.0.1.jar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        run: docker build \
          --build-arg SPRING_DATASOURCE_URL=${{ secrets.MONETA_DB_URL }} \
          --build-arg SPRING_DATASOURCE_USERNAME=${{ secrets.MONETA_DB_USER }} \
          --build-arg SPRING_DATASOURCE_PASSWORD=${{ secrets.MONETA_DB_PASSWORD }} \
          --build-arg EXCHANGE_RATE_API_KEY=${{ secrets.EXCHANGE_API_KEY }} \
          --build-arg FINNHUB_IO_API_KEY=${{ secrets.FINNHUB_API_KEY }} \
          --build-arg POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }} \
          --build-arg SPRING_EMAIL_PASSWORD=${{ secrets.MONETA_EMAIL_AUTH }} \
          -t monetainvest/moneta-hub:latest .